sudo: false
dist: trusty
language: c++

addons:
  apt:
    update: on
    sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
    packages:
    - cmake
    - libxrandr-dev
    - libudev-dev
    - libopenal-dev
    - libflac-dev
    - libvorbis-dev
    - libenet-dev
    - libgtk-3-dev
    - g++-4.9
    - clang-3.6

before_script:
- eval "${MATRIX_EVAL}"
- mkdir build && cd build
- cmake .. -G"$GENERATOR" $CMAKE_FLAGS

script:
- sudo cmake --build . --target install

matrix:
  include:

  # Linux - gcc 4.9
  - os: linux
    compiler: gcc-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - GENERATOR="Unix Makefiles"
    - CMAKE_FLAGS=""

  # Linux - clang 3.4
  - os: linux
    compiler: clang-3.6
    env:
    - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
    - GENERATOR="Unix Makefiles"
    - CMAKE_FLAGS=""

  # macOS - Xcode 9
  - os: osx
    osx_image: xcode9
    env:
    - GENERATOR="Xcode"
    - CMAKE_FLAGS="-DSFML_BUILD_FRAMEWORKS=TRUE"

  # iOS - Xcode 9
  - os: osx
    osx_image: xcode9
    env:
    - GENERATOR="Xcode"
    - CMAKE_FLAGS="-DCMAKE_TOOLCHAIN_FILE=../cmake/toolchains/iOS.toolchain.cmake"

notifications:
  email: false